In [1]:
import pandas as pd
import numpy as np

"""
vehicle_id STRING 车辆唯一标志码
charge_start_time INT 充电开始时间
charge_end_time INT 充电结束时间
mileage FLOAT 充电开始时刻车辆仪表里程（km）
charge_start_soc INT 充电开始时刻动力电池 SOC
charge_end_soc INT 充电结束时刻动力电池 SOC
charge_start_U FLOAT 充电开始时刻动力电池总电压（V）
charge_end_U FLOAT 充电结束时刻动力电池总电压（V）
charge_start_I FLOAT 充电开始时刻动力电池总电流（A）
charge_end_I FLOAT 充电结束时刻动力电池总电流（A）
charge_max_temp FLOAT 充电过程中电池系统温度探针最大值（℃）
charge_min_temp FLOAT 充电过程中电池系统温度探针最小值（℃）
charge_energy FLOAT 此充电过程的充电能量（kWh）
"""

data = pd.read_csv('data/predict_data_e_train.csv')
data = data.sample(frac=1) # 打乱顺序
data[data == 0] = np.nan
data.head()

,vehicle_id,charge_start_time,charge_end_time,mileage,charge_start_soc,charge_end_soc,charge_start_U,charge_end_U,charge_start_I,charge_end_I,charge_max_temp,charge_min_temp,charge_energy
677,3,20180307133055,20180307134535,155903.0,82.0,84.0,372.9,374.5,-8.0,-7.9,17.0,12.0,0.724
131,1,20180114214019,20180115041138,81508.6,41.2,100.0,364.4,398.0,-7.7,-7.7,14.0,7.0,18.852
294,2,20180520193034,20180521041414,65676.3,23.0,97.0,343.8,397.0,-7.7,-5.1,30.0,26.0,27.567
665,3,20180303080625,20180303091615,155212.0,56.0,67.0,347.5,358.1,-8.6,-8.4,7.0,4.0,3.449
763,3,20180601023558,20180601024809,170840.0,60.0,62.0,351.4,353.4,-8.4,-8.5,31.0,28.0,0.608

In [2]:
data.isnull().sum()

vehicle_id             0
charge_start_time      0
charge_end_time        0
mileage                0
charge_start_soc      27
charge_end_soc       198
charge_start_U         0
charge_end_U         150
charge_start_I         0
charge_end_I         331
charge_max_temp        7
charge_min_temp      448
charge_energy         17
dtype: int64

In [3]:
data = data.dropna(subset=['charge_energy'])
data.head()

,vehicle_id,charge_start_time,charge_end_time,mileage,charge_start_soc,charge_end_soc,charge_start_U,charge_end_U,charge_start_I,charge_end_I,charge_max_temp,charge_min_temp,charge_energy
677,3,20180307133055,20180307134535,155903.0,82.0,84.0,372.9,374.5,-8.0,-7.9,17.0,12.0,0.724
131,1,20180114214019,20180115041138,81508.6,41.2,100.0,364.4,398.0,-7.7,-7.7,14.0,7.0,18.852
294,2,20180520193034,20180521041414,65676.3,23.0,97.0,343.8,397.0,-7.7,-5.1,30.0,26.0,27.567
665,3,20180303080625,20180303091615,155212.0,56.0,67.0,347.5,358.1,-8.6,-8.4,7.0,4.0,3.449
763,3,20180601023558,20180601024809,170840.0,60.0,62.0,351.4,353.4,-8.4,-8.5,31.0,28.0,0.608

In [4]:
data.isnull().sum()

vehicle_id             0
charge_start_time      0
charge_end_time        0
mileage                0
charge_start_soc      27
charge_end_soc       198
charge_start_U         0
charge_end_U         137
charge_start_I         0
charge_end_I         317
charge_max_temp        7
charge_min_temp      448
charge_energy          0
dtype: int64

In [5]:
data.to_csv('data/train.csv')